# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a19360ca34fec0b17302d80f4fb0804"
name = "Sovendus Voucher Network"
handle = "sovendus-voucher-network-2"
application_url = "https://manage-refugees-escape-int.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testsovendus.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://manage-refugees-escape-int.trycloudflare.com/auth/callback",
  "https://manage-refugees-escape-int.trycloudflare.com/auth/shopify/callback",
  "https://manage-refugees-escape-int.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
